### ISSUE TITLE
[Feature] Delete Laps

### ISSUE THREAD

**Issue by YunPC** [yeongjong310/stopwatch#10]
모든 시간 기록을 지우는 함수

**Comment by ulgoon** [comment]
> 모든 시간 기록을 지우는 함수

서브태스크를 만들어 관리하면 더 편할 것 같아요^^

**Comment by YunPC** [comment]
서브태스크를 만든다는게 기능 명세를 더 세부적으로 하라는 말씀이신가요? @ulgoon

**Comment by ulgoon** [comment]
> 서브태스크를 만든다는게 기능 명세를 더 세부적으로 하라는 말씀이신가요? @ulgoon

예를 들면 모든 시간 기록을 지우는 함수라는 것을 내용이라고 한다면
이 함수를 구현하기 위해 필요한 작업들을
작업단위를 잘라 
- [ ] Task 1
- [ ] Task 2
로 표현하셔서 현재 진행상황에 대해 디테일하게 알 수 있도록 하면 좋아요^^
